-- Copyright 2018-2019, https://beingtechie.io

-- Script: db-setup-roles.sql
-- Description: Create roles and permissions specific tables and grant privileges
-- Version: 1.0
-- Author: Thribhuvan Krishnamurthy

-- # Step 1 - GROUPS table
DROP TABLE IF EXISTS proman.GROUPS CASCADE;
CREATE TABLE IF NOT EXISTS proman.GROUPS (
	ID SMALLSERIAL PRIMARY KEY,
	UUID SMALLINT NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	DESCRIPTION VARCHAR(200),
	CREATED_BY VARCHAR(100) NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE proman.GROUPS IS 'Table to capture groups';
COMMENT ON COLUMN proman.GROUPS.ID IS 'Auto generated PK identifier';
COMMENT ON COLUMN proman.GROUPS.UUID IS 'Unique identifier used as reference by external systems';
COMMENT ON COLUMN proman.GROUPS.NAME IS 'Unique name of the group';
COMMENT ON COLUMN proman.GROUPS.DESCRIPTION IS 'Description of the group';
COMMENT ON COLUMN proman.GROUPS.CREATED_BY IS 'User who inserted this record';
COMMENT ON COLUMN proman.GROUPS.CREATED_AT IS 'Point in time when this record was inserted';

ALTER TABLE proman.GROUPS OWNER TO proman_dba;
ALTER TABLE proman.GROUPS ADD CONSTRAINT UK_GROUPS_UUID UNIQUE(UUID);
GRANT ALL ON proman.GROUPS TO proman_dba;
GRANT SELECT,INSERT,UPDATE ON proman.GROUPS TO proman_dev;

-- # Step 2 - PERMISSIONS table
DROP TABLE IF EXISTS proman.PERMISSIONS;
CREATE TABLE IF NOT EXISTS proman.PERMISSIONS (
	ID SMALLSERIAL PRIMARY KEY,
	UUID SMALLINT NOT NULL,
	GROUP_ID SMALLINT NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	DESCRIPTION VARCHAR(200),
	CREATED_BY VARCHAR(100) NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE proman.PERMISSIONS IS 'Table to define permissions mapped to a group';
COMMENT ON COLUMN proman.PERMISSIONS.ID IS 'Auto generated PK identifier';
COMMENT ON COLUMN proman.PERMISSIONS.UUID IS 'Unique identifier used as reference by external systems';
COMMENT ON COLUMN proman.PERMISSIONS.GROUP_ID IS 'Group that this permission is mapped to';
COMMENT ON COLUMN proman.PERMISSIONS.NAME IS 'Unique name of the permission';
COMMENT ON COLUMN proman.PERMISSIONS.DESCRIPTION IS 'Description of the permission';
COMMENT ON COLUMN proman.PERMISSIONS.CREATED_BY IS 'User who inserted this record';
COMMENT ON COLUMN proman.PERMISSIONS.CREATED_AT IS 'Point in time when this record was inserted';

ALTER TABLE proman.PERMISSIONS OWNER TO proman_dba;
ALTER TABLE proman.PERMISSIONS ADD CONSTRAINT UK_PERMISSIONS_UUID UNIQUE(UUID);
ALTER TABLE proman.PERMISSIONS ADD CONSTRAINT FK_PERMISSIONS_GROUP_ID FOREIGN KEY(GROUP_ID) REFERENCES proman.GROUPS(ID);
GRANT ALL ON proman.PERMISSIONS TO proman_dba;
GRANT SELECT,INSERT,UPDATE ON proman.PERMISSIONS TO proman_dev;

-- # Step 3 - ROLES table
DROP TABLE IF EXISTS proman.ROLES;
CREATE TABLE IF NOT EXISTS proman.ROLES (
   ID SMALLSERIAL PRIMARY KEY,
   UUID SMALLINT NOT NULL,
   VERSION SERIAL NOT NULL,
   NAME VARCHAR(50) NOT NULL,
   DESCRIPTION VARCHAR(200),
   ACTIVE BOOLEAN NOT NULL,
   CREATED_BY VARCHAR(100) NOT NULL,
   CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   MODIFIED_BY VARCHAR(100),
   MODIFIED_AT TIMESTAMP
);
COMMENT ON TABLE proman.ROLES IS 'Table to define roles';
COMMENT ON COLUMN proman.ROLES.ID IS 'Auto generated PK identifier';
COMMENT ON COLUMN proman.ROLES.UUID IS 'Unique identifier used as reference by external systems';
COMMENT ON COLUMN proman.ROLES.VERSION IS 'Versioning for optimistic locking';
COMMENT ON COLUMN proman.ROLES.NAME IS 'Unique name of the role';
COMMENT ON COLUMN proman.ROLES.DESCRIPTION IS 'Description of the role';
COMMENT ON COLUMN proman.ROLES.ACTIVE IS 'Active status of the role - INACTIVE(0), ACTIVE (1)';
COMMENT ON COLUMN proman.ROLES.CREATED_BY IS 'User who inserted this record';
COMMENT ON COLUMN proman.ROLES.CREATED_AT IS 'Point in time when this record was inserted';
COMMENT ON COLUMN proman.ROLES.MODIFIED_BY IS 'User who modified this record';
COMMENT ON COLUMN proman.ROLES.MODIFIED_AT IS 'Point in time when this record was modified';

ALTER TABLE proman.ROLES OWNER TO proman_dba;
ALTER TABLE proman.ROLES ADD CONSTRAINT UK_ROLES_UUID UNIQUE(UUID);
ALTER TABLE proman.ROLES ADD CONSTRAINT UK_ROLES_NAME UNIQUE(NAME);
GRANT ALL ON proman.ROLES TO proman_dba;
GRANT SELECT,INSERT,UPDATE ON proman.ROLES TO proman_dev;

-- # Step 4 - ROLE_PERMISSIONS table
DROP TABLE IF EXISTS proman.ROLE_PERMISSIONS CASCADE;
CREATE TABLE IF NOT EXISTS proman.ROLE_PERMISSIONS (
   ID SMALLSERIAL PRIMARY KEY,
   ROLE_ID SMALLINT NOT NULL,
   PERMISSION_ID SMALLINT NOT NULL,
   CREATED_BY VARCHAR(100) NOT NULL,
   CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE proman.ROLE_PERMISSIONS IS 'Table to define role and permissions mapping';
COMMENT ON COLUMN proman.ROLE_PERMISSIONS.ID IS 'Auto generated PK identifier';
COMMENT ON COLUMN proman.ROLE_PERMISSIONS.ROLE_ID IS 'Role that has permissions mapped';
COMMENT ON COLUMN proman.ROLE_PERMISSIONS.PERMISSION_ID IS 'Permission mapped to the role';
COMMENT ON COLUMN proman.ROLES.CREATED_BY IS 'User who inserted this record';
COMMENT ON COLUMN proman.ROLES.CREATED_AT IS 'Point in time when this record was inserted';

ALTER TABLE proman.ROLE_PERMISSIONS OWNER TO proman_dba;
ALTER TABLE proman.ROLE_PERMISSIONS ADD CONSTRAINT FK_ROLE_PERMISSIONS_ROLE_ID FOREIGN KEY(ROLE_ID) REFERENCES proman.ROLES(ID);
ALTER TABLE proman.ROLE_PERMISSIONS ADD CONSTRAINT FK_ROLE_PERMISSIONS_PERMISSION_ID FOREIGN KEY(PERMISSION_ID) REFERENCES proman.PERMISSIONS(ID);
GRANT ALL ON proman.ROLE_PERMISSIONS TO proman_dba;
GRANT SELECT,INSERT,UPDATE,DELETE ON proman.ROLE_PERMISSIONS TO proman_dev;

-- # Step 5 - Commit Transaction
COMMIT;

-- ********** End of setup **********