-- Copyright 2018-2019, https://beingtechie.io

-- Script: db-setup-boards.sql
-- Description: Create movies specific tables and grant privileges
-- Version: 1.0
-- Author: Thribhuvan Krishnamurthy

-- # Step 1 - CITIES table

DROP TABLE IF EXISTS movieapp.CITIES CASCADE;
CREATE TABLE IF NOT EXISTS movieapp.CITIES (
	ID SERIAL PRIMARY KEY,
    CODE VARCHAR(3) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    CREATED_BY VARCHAR(100) NOT NULL DEFAULT CURRENT_USER,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE movieapp.CITIES IS 'Table to capture CITIES';
COMMENT ON COLUMN movieapp.CITIES.ID IS 'Auto generated PK identifier';
COMMENT ON COLUMN movieapp.CITIES.CODE IS 'Unique code for the City';
COMMENT ON COLUMN movieapp.CITIES.NAME IS 'Name of the city';
COMMENT ON COLUMN movieapp.CITIES.CREATED_BY IS 'User who inserted this record';
COMMENT ON COLUMN movieapp.CITIES.CREATED_AT IS 'Point in time when this record was inserted';

ALTER TABLE movieapp.CITIES OWNER TO postgres;
ALTER TABLE movieapp.CITIES ADD CONSTRAINT UK_CITIES_CODE UNIQUE(CODE);

-- # Step 2 - GENRES table

DROP TABLE IF EXISTS movieapp.GENRES CASCADE;
CREATE TABLE IF NOT EXISTS movieapp.GENRES (
	ID SERIAL PRIMARY KEY,
    UUID VARCHAR(36) NOT NULL,
    GENRE VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(1000),
    CREATED_BY VARCHAR(100) NOT NULL DEFAULT CURRENT_USER,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE movieapp.GENRES IS 'Table to capture GENRES';
COMMENT ON COLUMN movieapp.GENRES.ID IS 'Auto generated PK identifier';
COMMENT ON COLUMN movieapp.GENRES.UUID IS 'Unique identifier used as reference by external systems';
COMMENT ON COLUMN movieapp.GENRES.GENRE IS 'Title of the genre';
COMMENT ON COLUMN movieapp.GENRES.DESCRIPTION IS 'Description of the genre';
COMMENT ON COLUMN movieapp.GENRES.CREATED_BY IS 'User who inserted this record';
COMMENT ON COLUMN movieapp.GENRES.CREATED_AT IS 'Point in time when this record was inserted';

ALTER TABLE movieapp.GENRES OWNER TO postgres;
ALTER TABLE movieapp.GENRES ADD CONSTRAINT UK_GENRES_GENRE UNIQUE(GENRE);

-- # Step 3 - COUPONS table

DROP TABLE IF EXISTS movieapp.COUPONS CASCADE;
CREATE TABLE IF NOT EXISTS movieapp.COUPONS (
	ID SERIAL PRIMARY KEY,
    CODE VARCHAR(10) NOT NULL,
    DISCOUNT_PERCENTAGE NUMERIC(3,0) DEFAULT 0,
    DESCRIPTION VARCHAR(1000),
    CREATED_BY VARCHAR(100) NOT NULL DEFAULT CURRENT_USER,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE movieapp.COUPONS IS 'Table to capture COUPONS';
COMMENT ON COLUMN movieapp.COUPONS.ID IS 'Auto generated PK identifier';
COMMENT ON COLUMN movieapp.COUPONS.CODE IS 'Code of the coupon';
COMMENT ON COLUMN movieapp.COUPONS.DISCOUNT_PERCENTAGE IS 'Discount percentage of the Coupon';
COMMENT ON COLUMN movieapp.COUPONS.DESCRIPTION IS 'Description of the coupon';
COMMENT ON COLUMN movieapp.COUPONS.CREATED_BY IS 'User who inserted this record';
COMMENT ON COLUMN movieapp.COUPONS.CREATED_AT IS 'Point in time when this record was inserted';

ALTER TABLE movieapp.COUPONS OWNER TO postgres;
ALTER TABLE movieapp.COUPONS ADD CONSTRAINT UK_COUPONS_CODE UNIQUE(CODE);

-- # Step 3 - MOVIES table

DROP TABLE IF EXISTS movieapp.MOVIES CASCADE;
CREATE TABLE IF NOT EXISTS movieapp.MOVIES (
	ID SERIAL PRIMARY KEY,
    UUID VARCHAR(36) NOT NULL,
    VERSION SERIAL NOT NULL,
    TITLE VARCHAR(100) NOT NULL,
    DURATION SMALLINT NOT NULL,
    STORYLINE VARCHAR(2000) NOT NULL,
    POSTER_URL VARCHAR(2000) NOT NULL,
    TRAILER_URL VARCHAR(2000) NOT NULL,
    WIKI_URL VARCHAR(2000),
    RELEASE_AT TIMESTAMP NOT NULL,
    CENSOR_BOARD_RATING VARCHAR(3) NOT NULL,
    RATING NUMERIC(3,1) DEFAULT 0,
    STATUS VARCHAR(30) NOT NULL,
    CREATED_BY VARCHAR(100) NOT NULL DEFAULT CURRENT_USER,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY VARCHAR(100) NULL,
    MODIFIED_AT TIMESTAMP NULL
);
COMMENT ON TABLE movieapp.MOVIES IS 'Table to capture MOVIES';
COMMENT ON COLUMN movieapp.MOVIES.ID IS 'Auto generated PK identifier';
COMMENT ON COLUMN movieapp.MOVIES.UUID IS 'Unique identifier used as reference by external systems';
COMMENT ON COLUMN movieapp.MOVIES.VERSION IS 'Versioning for optimistic locking';
COMMENT ON COLUMN movieapp.MOVIES.TITLE IS 'Title of the movie';
COMMENT ON COLUMN movieapp.MOVIES.DURATION IS 'Duration (in minutes) of the movie';
COMMENT ON COLUMN movieapp.MOVIES.STORYLINE IS 'Storyline of the movie';
COMMENT ON COLUMN movieapp.MOVIES.POSTER_URL IS 'Poster url of the movie';
COMMENT ON COLUMN movieapp.MOVIES.TRAILER_URL IS 'Poster url of the movie';
COMMENT ON COLUMN movieapp.MOVIES.WIKI_URL IS 'Wiki url of the movie';
COMMENT ON COLUMN movieapp.MOVIES.RELEASE_AT IS 'Point in time when this movie will be release';
COMMENT ON COLUMN movieapp.MOVIES.CENSOR_BOARD_RATING IS 'Rating of the movie issued by Censor Board - U, A, UA';
COMMENT ON COLUMN movieapp.MOVIES.RATING IS 'Average rating provided by the film critics for the movie';
COMMENT ON COLUMN movieapp.MOVIES.STATUS IS 'Status of the movie - PUBLISHED, RELEASED, CLOSED, DELETED';
COMMENT ON COLUMN movieapp.MOVIES.CREATED_BY IS 'User who inserted this record';
COMMENT ON COLUMN movieapp.MOVIES.CREATED_AT IS 'Point in time when this record was inserted';
COMMENT ON COLUMN movieapp.MOVIES.MODIFIED_BY IS 'User who modified this record';
COMMENT ON COLUMN movieapp.MOVIES.MODIFIED_AT IS 'Point in time when this record was modified';

ALTER TABLE movieapp.MOVIES OWNER TO postgres;

-- # Step 4 - MOVIE_GENRES table
DROP TABLE IF EXISTS movieapp.MOVIE_GENRES CASCADE;
CREATE TABLE IF NOT EXISTS movieapp.MOVIE_GENRES (
   ID SERIAL PRIMARY KEY,
   MOVIE_ID INTEGER NOT NULL,
   GENRE_ID INTEGER NOT NULL,
   CREATED_BY VARCHAR(100) NOT NULL DEFAULT CURRENT_USER,
   CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE movieapp.MOVIE_GENRES IS 'Table to map movie with genres';
COMMENT ON COLUMN movieapp.MOVIE_GENRES.ID IS 'Auto generated PK identifier';
COMMENT ON COLUMN movieapp.MOVIE_GENRES.MOVIE_ID IS 'Movie that has these artists';
COMMENT ON COLUMN movieapp.MOVIE_GENRES.GENRE_ID IS 'Genre that the movie belongs to';
COMMENT ON COLUMN movieapp.MOVIE_GENRES.CREATED_BY IS 'User who inserted this record';
COMMENT ON COLUMN movieapp.MOVIE_GENRES.CREATED_AT IS 'Point in time when this record was inserted';

ALTER TABLE movieapp.MOVIE_GENRES OWNER TO postgres;
ALTER TABLE movieapp.MOVIE_GENRES ADD CONSTRAINT FK_MOVIE_GENRES_MOVIE_ID FOREIGN KEY(MOVIE_ID) REFERENCES movieapp.MOVIES(ID);
ALTER TABLE movieapp.MOVIE_GENRES ADD CONSTRAINT FK_MOVIE_GENRES_GENRE_ID FOREIGN KEY(GENRE_ID) REFERENCES movieapp.GENRES(ID);

-- # Step 5 - ARTISTS table
DROP TABLE IF EXISTS movieapp.ARTISTS CASCADE;
CREATE TABLE movieapp.ARTISTS(
	ID SERIAL PRIMARY KEY,
	UUID VARCHAR(36) NOT NULL,
	VERSION SERIAL NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    TYPE VARCHAR(50) NOT NULL,
    PROFILE_DESCRIPTION VARCHAR(2000),
    PROFILE_PICTURE_URL VARCHAR(2000) NOT NULL,
    WIKI_URL VARCHAR(2000),
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
	CREATED_BY VARCHAR(100) NOT NULL DEFAULT CURRENT_USER,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_BY VARCHAR(100),
	MODIFIED_AT TIMESTAMP
);
COMMENT ON TABLE movieapp.ARTISTS IS 'Table to capture Artists';
COMMENT ON COLUMN movieapp.ARTISTS.ID IS 'Auto generated PK identifier';
COMMENT ON COLUMN movieapp.ARTISTS.UUID IS 'Unique identifier used as reference by external systems';
COMMENT ON COLUMN movieapp.ARTISTS.VERSION IS 'Versioning for optimistic locking';
COMMENT ON COLUMN movieapp.ARTISTS.FIRST_NAME IS 'First name of an artist';
COMMENT ON COLUMN movieapp.ARTISTS.LAST_NAME IS 'Last name of an artist';
COMMENT ON COLUMN movieapp.ARTISTS.TYPE IS 'Type of an artist - DIRECTOR, PRODUCER, ACTOR, CINEMATOGRAPHER, MUSICIAN, STUNTMAN';
COMMENT ON COLUMN movieapp.ARTISTS.PROFILE_DESCRIPTION IS 'Profile description of an artist';
COMMENT ON COLUMN movieapp.ARTISTS.PROFILE_PICTURE_URL IS 'Profile picture url of an artist';
COMMENT ON COLUMN movieapp.ARTISTS.WIKI_URL IS 'Wiki url of an artist';
COMMENT ON COLUMN movieapp.ARTISTS.ACTIVE IS 'Active status of an artist - INACTIVE(0), ACTIVE(1)';
COMMENT ON COLUMN movieapp.ARTISTS.CREATED_BY IS 'User who inserted this record';
COMMENT ON COLUMN movieapp.ARTISTS.CREATED_AT IS 'Point in time when this record was inserted';
COMMENT ON COLUMN movieapp.ARTISTS.MODIFIED_BY IS 'User who modified this record';
COMMENT ON COLUMN movieapp.ARTISTS.MODIFIED_AT IS 'Point in time when this record was modified';

ALTER TABLE movieapp.ARTISTS OWNER TO postgres;

-- # Step 6 - MOVIE_ARTISTS table
DROP TABLE IF EXISTS movieapp.MOVIE_ARTISTS CASCADE;
CREATE TABLE IF NOT EXISTS movieapp.MOVIE_ARTISTS (
   ID SERIAL PRIMARY KEY,
   MOVIE_ID INTEGER NOT NULL,
   ARTIST_ID INTEGER NOT NULL,
   CREATED_BY VARCHAR(100) NOT NULL DEFAULT CURRENT_USER,
   CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE movieapp.MOVIE_ARTISTS IS 'Table to map movie with artists';
COMMENT ON COLUMN movieapp.MOVIE_ARTISTS.ID IS 'Auto generated PK identifier';
COMMENT ON COLUMN movieapp.MOVIE_ARTISTS.MOVIE_ID IS 'Movie that has these artists';
COMMENT ON COLUMN movieapp.MOVIE_ARTISTS.ARTIST_ID IS 'Artists who will be mapped to the Movie';
COMMENT ON COLUMN movieapp.MOVIE_ARTISTS.CREATED_BY IS 'User who inserted this record';
COMMENT ON COLUMN movieapp.MOVIE_ARTISTS.CREATED_AT IS 'Point in time when this record was inserted';

ALTER TABLE movieapp.MOVIE_ARTISTS OWNER TO postgres;
ALTER TABLE movieapp.MOVIE_ARTISTS ADD CONSTRAINT FK_MOVIE_ARTISTS_MOVIE_ID FOREIGN KEY(MOVIE_ID) REFERENCES movieapp.MOVIES(ID);
ALTER TABLE movieapp.MOVIE_ARTISTS ADD CONSTRAINT FK_MOVIE_ARTISTS_ARTIST_ID FOREIGN KEY(ARTIST_ID) REFERENCES movieapp.ARTISTS(ID);

-- # Step 7 - THEATRES table
DROP TABLE IF EXISTS movieapp.THEATRES CASCADE;
CREATE TABLE movieapp.THEATRES(
	ID SERIAL PRIMARY KEY,
	UUID VARCHAR(36) NOT NULL,
	VERSION SERIAL NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    POSTAL_ADDRESS VARCHAR(2000),
    CITY_CODE VARCHAR(3) NOT NULL,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
	CREATED_BY VARCHAR(100) NOT NULL DEFAULT CURRENT_USER,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_BY VARCHAR(100),
	MODIFIED_AT TIMESTAMP
);
COMMENT ON TABLE movieapp.THEATRES IS 'Table to capture Theatres';
COMMENT ON COLUMN movieapp.THEATRES.ID IS 'Auto generated PK identifier';
COMMENT ON COLUMN movieapp.THEATRES.UUID IS 'Unique identifier used as reference by external systems';
COMMENT ON COLUMN movieapp.THEATRES.VERSION IS 'Versioning for optimistic locking';
COMMENT ON COLUMN movieapp.THEATRES.NAME IS 'name of the theatre';
COMMENT ON COLUMN movieapp.THEATRES.POSTAL_ADDRESS IS 'Postal address of the theatre';
COMMENT ON COLUMN movieapp.THEATRES.CITY_CODE IS 'City to which the theatre belongs to';
COMMENT ON COLUMN movieapp.THEATRES.ACTIVE IS 'Active status of the theatre';
COMMENT ON COLUMN movieapp.THEATRES.CREATED_BY IS 'User who inserted this record';
COMMENT ON COLUMN movieapp.THEATRES.CREATED_AT IS 'Point in time when this record was inserted';
COMMENT ON COLUMN movieapp.THEATRES.MODIFIED_BY IS 'User who modified this record';
COMMENT ON COLUMN movieapp.THEATRES.MODIFIED_AT IS 'Point in time when this record was modified';

ALTER TABLE movieapp.THEATRES OWNER TO postgres;

-- # Step 8 - MOVIE_SHOWS table
DROP TABLE IF EXISTS movieapp.SHOWS CASCADE;
CREATE TABLE movieapp.SHOWS(
	ID SERIAL PRIMARY KEY,
	UUID VARCHAR(36) NOT NULL,
	VERSION SERIAL NOT NULL,
	MOVIE_ID INTEGER NOT NULL,
    THEATRE_ID INTEGER NOT NULL,
    START_TIME TIMESTAMP NOT NULL,
    END_TIME TIMESTAMP NOT NULL,
    LANG VARCHAR(50) NOT NULL,
    UNIT_PRICE NUMERIC(6,2) NOT NULL,
    TOTAL_SEATS SMALLINT NOT NULL,
    AVAILABLE_SEATS SMALLINT,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
	CREATED_BY VARCHAR(100) NOT NULL DEFAULT CURRENT_USER,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_BY VARCHAR(100),
	MODIFIED_AT TIMESTAMP
);
COMMENT ON TABLE movieapp.SHOWS IS 'Table to capture Movie Shows';
COMMENT ON COLUMN movieapp.SHOWS.ID IS 'Auto generated PK identifier';
COMMENT ON COLUMN movieapp.SHOWS.UUID IS 'Unique identifier used as reference by external systems';
COMMENT ON COLUMN movieapp.SHOWS.VERSION IS 'Versioning for optimistic locking';
COMMENT ON COLUMN movieapp.SHOWS.MOVIE_ID IS 'Movie that is part of this show';
COMMENT ON COLUMN movieapp.SHOWS.THEATRE_ID IS 'Theatre where movie is shown';
COMMENT ON COLUMN movieapp.SHOWS.START_TIME IS 'Show start time of the movie';
COMMENT ON COLUMN movieapp.SHOWS.END_TIME IS 'Show end time of the movie';
COMMENT ON COLUMN movieapp.SHOWS.LANG IS 'Language of the movie for this show';
COMMENT ON COLUMN movieapp.SHOWS.UNIT_PRICE IS 'Price of the movie for this show';
COMMENT ON COLUMN movieapp.SHOWS.TOTAL_SEATS IS 'Total seats for the show';
COMMENT ON COLUMN movieapp.SHOWS.AVAILABLE_SEATS IS 'Available seats for the show';
COMMENT ON COLUMN movieapp.SHOWS.ACTIVE IS 'Active status of the show';
COMMENT ON COLUMN movieapp.SHOWS.CREATED_BY IS 'User who inserted this record';
COMMENT ON COLUMN movieapp.SHOWS.CREATED_AT IS 'Point in time when this record was inserted';
COMMENT ON COLUMN movieapp.SHOWS.MODIFIED_BY IS 'User who modified this record';
COMMENT ON COLUMN movieapp.SHOWS.MODIFIED_AT IS 'Point in time when this record was modified';

ALTER TABLE movieapp.SHOWS OWNER TO postgres;
ALTER TABLE movieapp.SHOWS ADD CONSTRAINT FK_MOVIE_SHOWS_MOVIE_ID FOREIGN KEY(MOVIE_ID) REFERENCES movieapp.MOVIES(ID);
ALTER TABLE movieapp.SHOWS ADD CONSTRAINT FK_MOVIE_SHOWS_THEATRE_ID FOREIGN KEY(THEATRE_ID) REFERENCES movieapp.THEATRES(ID);


-- # Step 9 - SHOW_BOOKINGS table
DROP TABLE IF EXISTS movieapp.SHOW_BOOKINGS CASCADE;
CREATE TABLE movieapp.SHOW_BOOKINGS(
	ID SERIAL PRIMARY KEY,
	UUID VARCHAR(36) NOT NULL,
	VERSION SERIAL NOT NULL,
	CUSTOMER_ID INTEGER NOT NULL,
    SHOW_ID INTEGER NOT NULL,
    BOOKING_REF VARCHAR(30) NOT NULL,
    COUPON_CODE VARCHAR(10),
    TOTAL_SEATS SMALLINT NOT NULL,
    TOTAL_PRICE NUMERIC(8,2) NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    BOOKING_AT TIMESTAMP NOT NULL,
    CANCELLED_AT TIMESTAMP,
	CREATED_BY VARCHAR(100) NOT NULL DEFAULT CURRENT_USER,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_BY VARCHAR(100),
	MODIFIED_AT TIMESTAMP
);
COMMENT ON TABLE movieapp.SHOW_BOOKINGS IS 'Table to capture Movie Show Bookings';
COMMENT ON COLUMN movieapp.SHOW_BOOKINGS.ID IS 'Auto generated PK identifier';
COMMENT ON COLUMN movieapp.SHOW_BOOKINGS.UUID IS 'Unique identifier used as reference by external systems';
COMMENT ON COLUMN movieapp.SHOW_BOOKINGS.VERSION IS 'Versioning for optimistic locking';
COMMENT ON COLUMN movieapp.SHOW_BOOKINGS.CUSTOMER_ID IS 'Customer who has booked a seat';
COMMENT ON COLUMN movieapp.SHOW_BOOKINGS.SHOW_ID IS 'Movie show that has been booked for';
COMMENT ON COLUMN movieapp.SHOW_BOOKINGS.BOOKING_REF IS 'Booking reference number';
COMMENT ON COLUMN movieapp.SHOW_BOOKINGS.COUPON_CODE IS 'Coupon code applied while booking';
COMMENT ON COLUMN movieapp.SHOW_BOOKINGS.TOTAL_SEATS IS 'Total number of seats booked';
COMMENT ON COLUMN movieapp.SHOW_BOOKINGS.TOTAL_PRICE IS 'Total price for the tickets that were booked';
COMMENT ON COLUMN movieapp.SHOW_BOOKINGS.STATUS IS 'Status of the Booking - CONFIRMED,CANCELLED';
COMMENT ON COLUMN movieapp.SHOW_BOOKINGS.BOOKING_AT IS 'Point in time when this booking was confirmed';
COMMENT ON COLUMN movieapp.SHOW_BOOKINGS.CANCELLED_AT IS 'Point in time when this booking was cancelled';
COMMENT ON COLUMN movieapp.SHOW_BOOKINGS.CREATED_BY IS 'User who inserted this record';
COMMENT ON COLUMN movieapp.SHOW_BOOKINGS.CREATED_AT IS 'Point in time when this record was inserted';
COMMENT ON COLUMN movieapp.SHOW_BOOKINGS.MODIFIED_BY IS 'User who modified this record';
COMMENT ON COLUMN movieapp.SHOW_BOOKINGS.MODIFIED_AT IS 'Point in time when this record was modified';

ALTER TABLE movieapp.SHOW_BOOKINGS OWNER TO postgres;
ALTER TABLE movieapp.SHOW_BOOKINGS ADD CONSTRAINT UK_SHOW_BOOKINGS_BOOKING_REF UNIQUE(BOOKING_REF);
ALTER TABLE movieapp.SHOW_BOOKINGS ADD CONSTRAINT FK_SHOW_BOOKINGS_MOVIE_SHOW_ID FOREIGN KEY(SHOW_ID) REFERENCES movieapp.SHOWS(ID);
ALTER TABLE movieapp.SHOW_BOOKINGS ADD CONSTRAINT FK_SHOW_BOOKINGS_CUSTOMER_ID FOREIGN KEY(CUSTOMER_ID) REFERENCES movieapp.USERS(ID);

-- # Step 10 - BOOKING_TICKETS table
DROP TABLE IF EXISTS movieapp.BOOKING_TICKETS CASCADE;
CREATE TABLE IF NOT EXISTS movieapp.BOOKING_TICKETS (
   ID SERIAL PRIMARY KEY,
   BOOKING_ID INTEGER NOT NULL,
   TICKET_NUMBER VARCHAR(3) NOT NULL,
   CREATED_BY VARCHAR(100) NOT NULL DEFAULT CURRENT_USER,
   CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE movieapp.BOOKING_TICKETS IS 'Table to map movie with Booking Tickets';
COMMENT ON COLUMN movieapp.BOOKING_TICKETS.ID IS 'Auto generated PK identifier';
COMMENT ON COLUMN movieapp.BOOKING_TICKETS.BOOKING_ID IS 'Booking that this ticket belongs to';
COMMENT ON COLUMN movieapp.BOOKING_TICKETS.TICKET_NUMBER IS 'Ticket Number';
COMMENT ON COLUMN movieapp.BOOKING_TICKETS.CREATED_BY IS 'User who inserted this record';
COMMENT ON COLUMN movieapp.BOOKING_TICKETS.CREATED_AT IS 'Point in time when this record was inserted';

ALTER TABLE movieapp.BOOKING_TICKETS OWNER TO postgres;
ALTER TABLE movieapp.BOOKING_TICKETS ADD CONSTRAINT UK_BOOKING_TICKETS_BOOKING_TICKET_NUMBER UNIQUE(BOOKING_ID,TICKET_NUMBER);
ALTER TABLE movieapp.BOOKING_TICKETS ADD CONSTRAINT FK_BOOKING_TICKETS_SHOW_BOOKING_ID FOREIGN KEY(BOOKING_ID) REFERENCES movieapp.SHOW_BOOKINGS(ID);

-- # Step 11 - Commit Transaction
COMMIT;

-- ********** End of setup **********